version: "3"
services:
  postgres:
    build: postgres
    environment:
    - POSTGRES_PASSWORD=akvo
    volumes:
    - pg-data:/var/lib/postgresql/data
  authz:
    volumes:
      - pg-data:/pg-certs:ro
    environment:
      - PGSSLROOTCERT=/pg-certs/server.crt
      - UNILOG_DATABASE_NAME=u_unilog_events
      - UNILOG_DATABASE_HOST=postgres
      - UNILOG_DATABASE_USER=uniloguser
      - UNILOG_DATABASE_PASSWORD=uniloguserpassword
      - AUTHZ_DATABASE_URL=jdbc:postgresql://postgres/authzdb?user=authzuser&password=authzpasswd&ssl=true
      - GITHUB_HOST=http://fake-github:5000
      - GITHUB_TOKEN=any
      - GITHUB_REFRESH_EVERY_SECS=2
      - SENTRY_DSN=http://a-sentry-key:a-sentry-secret@wiremock-proxy:8080/sentry/213123
      - CONSUMER_PARALLELISM=5
    depends_on:
      - fake-github
  fake-github:
    build: fake-github
    entrypoint: sh -c "mkdir -p /html/repos/akvo/akvo-flow-server-config/zipball/ && cp /html/initial-github-config.zip /html/repos/akvo/akvo-flow-server-config/zipball/master && /http-server"
    ports:
      - 5000:5000
    volumes:
      - ./backend/fake-github:/html
  wiremock-proxy:
    image: rodolpheche/wiremock:2.16.0-alpine
    volumes:
      - ./wiremock:/etc/wiremock/files
    command: --root-dir /etc/wiremock/files --no-request-journal --verbose

volumes:
  pg-data: