version: "3"
services:
  postgres:
    ports:
    - "5432:5432"
  authz:
    build:
      context: backend
      dockerfile: dev/Dockerfile-dev
    environment:
      - SKIP_AUTHZ_METRICS_REGISTRATION=true
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
      #- ../akvo-flow-server-config/:/akvo-flow-server-config
    ports:
      - "47480:47480"
      - "3000:3000"
  wiremock-proxy:
    ports:
      - 8081:8080