@startuml

artifact db as "ElephantDB authz cluster" {
    node authzdb as "authz DB"
}

artifact db2 as "ElephantDB unilog cluster" {

    node unilog1 as "u_akvoflow-1"
    node unilog2 as "u_akvoflow-2"
    node unilog3 as "..."
}

artifact k8s as "k8s" {

    artifact api_pod as "API pod (multiple pods)" {

        node auth0 as "nginx auth0"

        node api as "api"

        api --> authzdb

        auth0 -[#00FF00]-> api

    }

    node internal as "k8s internal service
    (http://akvo-authz-api-internal)"
    internal -[#00FFFF]-> api

    artifact consumer_pod as "Consumer pod" {
        node consumer as "Unilog consumer"
        consumer --> authzdb
        consumer --> unilog1
        consumer --> unilog2
        consumer --> unilog3
    }

}

actor browser
node ingress as "Avko ingress"
browser -[#0000FF]-> ingress : https://authz.akvo.org/....
ingress -[#0000FF]-> auth0 : authz.akvo.org

@enduml
