---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akvo-authz
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: akvo-authz
  template:
    metadata:
      labels:
        run: akvo-authz
        akvo-authz-version: $TRAVIS_COMMIT
        app: akvo-authz
        environment: ${ENVIRONMENT}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
    spec:
      containers:
      - name: akvo-authz
        image: eu.gcr.io/akvo-lumen/akvo-authz:$TRAVIS_COMMIT
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: ${POD_CPU_REQUESTS}
            memory: ${POD_MEM_REQUESTS}
          limits:
            cpu: ${POD_CPU_LIMITS}
            memory: ${POD_MEM_LIMITS}
        env:
         - name: POD_NAME
           valueFrom:
             fieldRef:
               fieldPath: metadata.name
         - name: POD_NAMESPACE
           valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
         - name: APP_VERSION
           value: $TRAVIS_COMMIT
         - name: AUTHZ_PROFILE_TO_RUN
           value: "authz.profile/api"
         - name: ENV_NAME
           valueFrom:
             configMapKeyRef:
               name: akvo
               key: environment
         - name: AUTHZ_DATABASE_URL
           valueFrom:
             secretKeyRef:
               name: akvo-authz
               key: authz-database-url
         - name: GOOGLE_APPLICATION_CREDENTIALS
           value: "/secrets/cloudsql/credentials.json"
         - name: GITHUB_TOKEN
           valueFrom:
             secretKeyRef:
               name: akvo-authz
               key: github-auth-token
         - name: SENTRY_DSN
           valueFrom:
             secretKeyRef:
               name: akvo-authz
               key: sentry-dsn
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 90
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 90
        volumeMounts:
          - name: authz-secrets
            mountPath: "/secrets/cloudsql/credentials.json"
            subPath: "cloud-database-service-account.json"
            readOnly: true
      - name: akvo-authz-auth0-proxy
        image: eu.gcr.io/akvo-lumen/akvo-authz-nginx-auth0:$TRAVIS_COMMIT
        imagePullPolicy: Always
        ports:
          - containerPort: 8082
        resources:
          requests:
            cpu: ${PROXY_POD_CPU_REQUESTS}
            memory: ${PROXY_POD_MEM_REQUESTS}
          limits:
            cpu: ${PROXY_POD_CPU_LIMITS}
            memory: ${PROXY_POD_MEM_LIMITS}
        env:
          - name: SECRETS_MOUNT_PATH
            value: "/secrets"
          - name: AUTHZ_API_BACKEND_URL
            value: "http://localhost:3000"
          - name: OIDC_DISCOVERY_URL
            valueFrom:
              configMapKeyRef:
                name: flow-api
                key: oidc.discovery.url
          - name: OIDC_EXPECTED_ISSUER
            valueFrom:
              configMapKeyRef:
                name: flow-api
                key: oidc.expected.issuer
      volumes:
        - name: secrets
          secret:
            secretName: flow-api-secrets
        - name: authz-secrets
          secret:
            secretName: akvo-authz
