{
 "title": "Authz",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Request per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{run=\"akvo-authz\", path!=\"/healthz\"}[5m])) by (path, method)",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  },
  {
   "title": "95% latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_latency_seconds_bucket{run=\"akvo-authz\", path!=\"/healthz\"}[5m])) by (le,path,method))",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"akvo-authz-.*\", container_name!=\"akvo-authz-unilog-consumer\", container_name!=\"POD\"}",
     "legendFormat": "{{container_name}} - {{pod_name}} "
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",pod_name=~\"akvo-authz.*\", container_name!=\"akvo-authz-unilog-consumer\",namespace=\"default\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "{{container_name}} - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Restarts per 30 mins",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"akvo-authz.*\"}[30m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 }, "content": "# Consumer" },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"akvo-authz-unilog.*\", container_name!=\"POD\"}",
     "legendFormat": "{{pod_name}} "
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",pod_name=~\"akvo-authz-unilog.*\",namespace=\"default\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Last run",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 18 },
   "targets": [
    {
     "expr": "event_last_run{app=\"akvo-authz\", db_name=\"global\"}  * 1000",
     "legendFormat": "finish"
    },
    {
     "expr": "event_last_success{app=\"akvo-authz\", db_name=\"global\"} * 1000",
     "legendFormat": "success"
    },
    {
     "expr": "event_last_run{app=\"akvo-authz\", db_name=\"global\"}  * 1000",
     "legendFormat": "start"
    }
   ]
  },
  {
   "title": "Unilog processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(event_tenant_duration_bucket{run=\"akvo-authz-unilog-consumer\"}[5m])) by (le,db_name))",
     "legendFormat": "{{db_name}} "
    }
   ]
  },
  {
   "title": "Total events read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "event_total{app=\"akvo-authz\"}",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Total events processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "event_valid{app=\"akvo-authz\"}",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Unilog offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 26 },
   "targets": [
    {
     "expr": "event_unilog_offset{app=\"akvo-authz\"}",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Events queued up",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 26 },
   "targets": [
    {
     "expr": "event_queued_up{app=\"akvo-authz\"}",
     "legendFormat": "{{flow_instance}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"akvo-authz.*\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "{{container_name}} - {{pod_name}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"akvo-authz.*\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "{{container_name}} - {{pod_name}}"
    }
   ]
  }
 ]
}