apiVersion: v1
kind: Service
metadata:
  name: akvo-authz
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    run: akvo-authz
---
apiVersion: v1
kind: Service
metadata:
  name: akvo-authz-auth0
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    run: akvo-authz
---
apiVersion: v1
kind: Service
metadata:
  name: akvo-authz-api-internal
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    run: akvo-authz
